### ISSUE TITLE
ERROR  When running this code.

### ISSUE THREAD

**Issue by Chendaqiang01** [YiLunLee/missing_aware_prompts#15]
INFO - ViLT - Running command 'main'
INFO - ViLT - Started
Global seed set to 0
INFO - lightning - Global seed set to 0
ERROR - ViLT - Failed after 0:01:33!
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/root/missing_aware_prompts-main/run.py", line 16, in main
    dm = MTDataModule(_config, dist=True)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 49, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/root/missing_aware_prompts-main/vilt/datamodules/multitask_datamodule.py", line 19, in __init__
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/root/missing_aware_prompts-main/vilt/datamodules/multitask_datamodule.py", line 19, in <dictcomp>
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
KeyError: 'coco'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/root/miniconda3/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'
python-BaseException

looking for your reply,thanks!

**Comment by JackieQiang** [comment]
@Chendaqiang01 how to fix this problem?  I  meet same problem.
